apiVersion: v2
name: filebeat
description: A Helm chart for Kubernetes for Filebeat + 10x Observability engine
keywords:
  - 10x
  - log10x
  - logging
  - elastic
  - filebeat
version: 0.3.0
appVersion: 0.4.0
icon: https://raw.githubusercontent.com/log-10x/elastic-helm-charts/main/icon.png
home: https://github.com/log-10x/elastic-helm-charts
sources:
  - https://github.com/log-10x/elastic-helm-charts
  - https://github.com/log-10x/docker-images
  - https://github.com/elastic/beats
maintainers:
  - name: Log10x
    email: engineering@log10x.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Upgraded 10x engine to 0.4.0"
    - kind: added
      description: "Documented output.console limitation with 10x stdout pipe"
